"""m0_initial_schema

Revision ID: 7253f352f69e
Revises: 
Create Date: 2026-09-06 22:21:06.904224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7253f352f69e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultural_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('element', sa.String(length=128), nullable=False),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('adoption_stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cultural_elements'))
    )
    op.create_index(op.f('ix_cultural_elements_world_id'), 'cultural_elements', ['world_id'], unique=False)
    op.create_table('ecological_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('terrain', sa.String(length=32), nullable=True),
    sa.Column('climate', sa.String(length=32), nullable=True),
    sa.Column('water', sa.String(length=32), nullable=True),
    sa.Column('flora_classes', sa.JSON(), nullable=True),
    sa.Column('fauna_classes', sa.JSON(), nullable=True),
    sa.Column('spiritual_resources', sa.JSON(), nullable=True),
    sa.Column('danger_level', sa.String(length=12), nullable=True),
    sa.Column('carrying_capacity', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ecological_regions'))
    )
    op.create_index(op.f('ix_ecological_regions_world_id'), 'ecological_regions', ['world_id'], unique=False)
    op.create_table('industries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('node_ref', sa.String(length=64), nullable=True),
    sa.Column('input_output', sa.JSON(), nullable=True),
    sa.Column('labor', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.JSON(), nullable=True),
    sa.Column('seasonality', sa.JSON(), nullable=True),
    sa.Column('risk', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries'))
    )
    op.create_index(op.f('ix_industries_world_id'), 'industries', ['world_id'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('settlement_ref', sa.String(length=64), nullable=True),
    sa.Column('owner_ref', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('members', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions'))
    )
    op.create_index(op.f('ix_institutions_world_id'), 'institutions', ['world_id'], unique=False)
    op.create_table('lineages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('lineage_type', sa.String(length=16), nullable=False),
    sa.Column('head_person_ref', sa.String(length=64), nullable=True),
    sa.Column('member_ids', sa.JSON(), nullable=True),
    sa.Column('history_ref', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineages'))
    )
    op.create_index(op.f('ix_lineages_world_id'), 'lineages', ['world_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('species', sa.String(length=32), nullable=True),
    sa.Column('birth_blessed_time', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('residence_ref', sa.String(length=64), nullable=True),
    sa.Column('occupation_ref', sa.String(length=64), nullable=True),
    sa.Column('lineage_ref', sa.String(length=64), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('relation_tags', sa.JSON(), nullable=True),
    sa.Column('llm_eligible', sa.Boolean(), nullable=False),
    sa.Column('demise', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index(op.f('ix_persons_world_id'), 'persons', ['world_id'], unique=False)
    op.create_table('population_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('species', sa.String(length=32), nullable=False),
    sa.Column('settlement_ref', sa.String(length=64), nullable=True),
    sa.Column('age_cohort', sa.String(length=16), nullable=True),
    sa.Column('occupation_group', sa.String(length=64), nullable=True),
    sa.Column('household_stats', sa.JSON(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_blessed_time', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_population_groups'))
    )
    op.create_index(op.f('ix_population_groups_world_id'), 'population_groups', ['world_id'], unique=False)
    op.create_table('resource_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('region_ref', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('yield_model', sa.JSON(), nullable=True),
    sa.Column('history_ref', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_nodes'))
    )
    op.create_index(op.f('ix_resource_nodes_world_id'), 'resource_nodes', ['world_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('settlement_type', sa.String(length=16), nullable=False),
    sa.Column('region_ref', sa.String(length=64), nullable=True),
    sa.Column('working_name', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('population_capacity', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index(op.f('ix_settlements_world_id'), 'settlements', ['world_id'], unique=False)
    op.create_table('system_configuration',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_configuration'))
    )
    op.create_table('timeline_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('blessed_time', sa.String(length=24), nullable=True),
    sa.Column('real_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('spotlight', sa.Boolean(), nullable=False),
    sa.Column('digest_text', sa.Text(), nullable=True),
    sa.Column('event_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_entries'))
    )
    op.create_index(op.f('ix_timeline_entries_world_id'), 'timeline_entries', ['world_id'], unique=False)
    op.create_table('tribulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.String(length=32), nullable=False),
    sa.Column('window_type', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('start_blessed_time', sa.String(length=24), nullable=True),
    sa.Column('end_blessed_time', sa.String(length=24), nullable=True),
    sa.Column('residual', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tribulations'))
    )
    op.create_index(op.f('ix_tribulations_world_id'), 'tribulations', ['world_id'], unique=False)
    op.create_table('world_runtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('world_bible_version', sa.String(length=16), nullable=False),
    sa.Column('world_bible_manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('simulation_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('world_seed_version', sa.String(length=32), nullable=True),
    sa.Column('runtime_status', sa.String(length=24), nullable=False),
    sa.Column('last_simulated_real_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_blessed_time', sa.String(length=32), nullable=True),
    sa.Column('current_time_ratio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_runtime')),
    sa.UniqueConstraint('world_id', name=op.f('uq_world_runtime_world_id'))
    )
    op.create_table('narrative_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('source_event_ids', sa.JSON(), nullable=False),
    sa.Column('renderer_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['world_runtime.world_id'], name=op.f('fk_narrative_records_world_id_world_runtime')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_narrative_records'))
    )
    op.create_table('runtime_lock',
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world_runtime.world_id'], name=op.f('fk_runtime_lock_world_id_world_runtime')),
    sa.PrimaryKeyConstraint('world_id', name=op.f('pk_runtime_lock'))
    )
    op.create_table('simulation_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('checkpoint_blessed_time', sa.String(length=32), nullable=True),
    sa.Column('world_state_hash', sa.String(length=64), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world_runtime.world_id'], name=op.f('fk_simulation_checkpoints_world_id_world_runtime')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_checkpoints'))
    )
    op.create_table('simulation_run',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_blessed_time', sa.String(length=32), nullable=True),
    sa.Column('committed_until', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('simulation_version', sa.String(length=32), nullable=False),
    sa.Column('seed_context', sa.JSON(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['world_runtime.world_id'], name=op.f('fk_simulation_run_world_id_world_runtime')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_simulation_run'))
    )
    op.create_table('time_ratio_history',
    sa.Column('ratio_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('real_effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blessed_effective_from', sa.String(length=32), nullable=True),
    sa.Column('ratio_value', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world_runtime.world_id'], name=op.f('fk_time_ratio_history_world_id_world_runtime')),
    sa.PrimaryKeyConstraint('ratio_id', name=op.f('pk_time_ratio_history'))
    )
    op.create_table('world_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_uid', sa.String(length=64), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('cause', sa.JSON(), nullable=False),
    sa.Column('effect', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('state_changes', sa.JSON(), nullable=False),
    sa.Column('blessed_time', sa.String(length=32), nullable=True),
    sa.Column('real_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('simulation_seed', sa.String(length=64), nullable=True),
    sa.Column('parent_event_ref', sa.String(length=64), nullable=True),
    sa.Column('supersedes_event_id', sa.String(length=64), nullable=True),
    sa.Column('reverses_event_id', sa.String(length=64), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world_runtime.world_id'], name=op.f('fk_world_events_world_id_world_runtime')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_events')),
    sa.UniqueConstraint('event_uid', name='uq_world_events_event_uid'),
    sa.UniqueConstraint('event_uid', name=op.f('uq_world_events_event_uid'))
    )
    op.create_table('world_state_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('event_ref', sa.String(length=64), nullable=True),
    sa.Column('blessed_time', sa.String(length=32), nullable=True),
    sa.Column('real_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['world_runtime.world_id'], name=op.f('fk_world_state_changes_world_id_world_runtime')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_state_changes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_state_changes')
    op.drop_table('world_events')
    op.drop_table('time_ratio_history')
    op.drop_table('simulation_run')
    op.drop_table('simulation_checkpoints')
    op.drop_table('runtime_lock')
    op.drop_table('narrative_records')
    op.drop_table('world_runtime')
    op.drop_index(op.f('ix_tribulations_world_id'), table_name='tribulations')
    op.drop_table('tribulations')
    op.drop_index(op.f('ix_timeline_entries_world_id'), table_name='timeline_entries')
    op.drop_table('timeline_entries')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_settlements_world_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_resource_nodes_world_id'), table_name='resource_nodes')
    op.drop_table('resource_nodes')
    op.drop_index(op.f('ix_population_groups_world_id'), table_name='population_groups')
    op.drop_table('population_groups')
    op.drop_index(op.f('ix_persons_world_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_lineages_world_id'), table_name='lineages')
    op.drop_table('lineages')
    op.drop_index(op.f('ix_institutions_world_id'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_industries_world_id'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_ecological_regions_world_id'), table_name='ecological_regions')
    op.drop_table('ecological_regions')
    op.drop_index(op.f('ix_cultural_elements_world_id'), table_name='cultural_elements')
    op.drop_table('cultural_elements')
    # ### end Alembic commands ###
